Improve stealth

diff --git a/src/var/lib/dpkg/info/openssh-client.postinst b/src/var/lib/dpkg/info/openssh-client.postinst
--- a/src/var/lib/dpkg/info/openssh-client.postinst
+++ b/src/var/lib/dpkg/info/openssh-client.postinst
@@ -43,7 +43,14 @@ if [ "$action" = configure ]; then
 	fi
 fi
 
-# Automatically added by dh_installdeb/13.11.4
+# Automatically added by dh_installtmpfiles/13.20
+if [ "$1" = "configure" ] || [ "$1" = "abort-upgrade" ] || [ "$1" = "abort-deconfigure" ] || [ "$1" = "abort-remove" ] ; then
+	if [ -x "$(command -v systemd-tmpfiles)" ]; then
+		systemd-tmpfiles ${DPKG_ROOT:+--root="$DPKG_ROOT"} --create openssh-client.conf || true
+	fi
+fi
+# End automatically added section
+# Automatically added by dh_installdeb/13.20
 dpkg-maintscript-helper rm_conffile /etc/ssh/moduli 1:7.9p1-8\~ -- "$@"
 # End automatically added section
 
diff --git a/src/var/lib/dpkg/info/systemd-timesyncd.postinst b/src/var/lib/dpkg/info/systemd-timesyncd.postinst
--- a/src/var/lib/dpkg/info/systemd-timesyncd.postinst
+++ b/src/var/lib/dpkg/info/systemd-timesyncd.postinst
@@ -23,12 +23,29 @@ if [ "$1" = configure ] && [ -z "$2" ]; then
     _adopt_conffile /etc/systemd/timesyncd.conf systemd-timesyncd
 fi
 
-# Automatically added by dh_installsysusers/13.11.4
+# Automatically added by dh_installsysusers/13.24.1
 if [ "$1" = "configure" ] || [ "$1" = "abort-upgrade" ] || [ "$1" = "abort-deconfigure" ] || [ "$1" = "abort-remove" ] ; then
    systemd-sysusers ${DPKG_ROOT:+--root="$DPKG_ROOT"} systemd-timesync.conf
 fi
 # End automatically added section
-# Automatically added by dh_installsystemd/13.11.4
+# Automatically added by dh_installsystemd/13.24.1
+if [ "$1" = "configure" ] || [ "$1" = "abort-upgrade" ] || [ "$1" = "abort-deconfigure" ] || [ "$1" = "abort-remove" ] ; then
+	# The following line should be removed in trixie or trixie+1
+	deb-systemd-helper unmask 'systemd-time-wait-sync.service' >/dev/null || true
+
+	# was-enabled defaults to true, so new installations run enable.
+	if deb-systemd-helper --quiet was-enabled 'systemd-time-wait-sync.service'; then
+		# Enables the unit on first installation, creates new
+		# symlinks on upgrades if the unit file has changed.
+		deb-systemd-helper enable 'systemd-time-wait-sync.service' >/dev/null || true
+	else
+		# Update the statefile to add new symlinks (if any), which need to be
+		# cleaned up on purge. Also remove old symlinks.
+		deb-systemd-helper update-state 'systemd-time-wait-sync.service' >/dev/null || true
+	fi
+fi
+# End automatically added section
+# Automatically added by dh_installsystemd/13.24.1
 if [ "$1" = "configure" ] || [ "$1" = "abort-upgrade" ] || [ "$1" = "abort-deconfigure" ] || [ "$1" = "abort-remove" ] ; then
 	# The following line should be removed in trixie or trixie+1
 	deb-systemd-helper unmask 'systemd-timesyncd.service' >/dev/null || true
@@ -45,7 +62,7 @@ if [ "$1" = "configure" ] || [ "$1" = "abort-upgrade" ] || [ "$1" = "abort-decon
 	fi
 fi
 # End automatically added section
-# Automatically added by dh_installsystemd/13.11.4
+# Automatically added by dh_installsystemd/13.24.1
 if [ "$1" = "configure" ] || [ "$1" = "abort-upgrade" ] || [ "$1" = "abort-deconfigure" ] || [ "$1" = "abort-remove" ] ; then
 	if [ -d /run/systemd/system ]; then
 		systemctl --system daemon-reload >/dev/null || true
@@ -54,7 +71,7 @@ if [ "$1" = "configure" ] || [ "$1" = "abort-upgrade" ] || [ "$1" = "abort-decon
 		else
 			_dh_action=start
 		fi
-		deb-systemd-invoke $_dh_action 'systemd-timesyncd.service' >/dev/null || true
+		deb-systemd-invoke $_dh_action 'systemd-time-wait-sync.service' 'systemd-timesyncd.service' >/dev/null || true
 	fi
 fi
 # End automatically added section
diff --git a/src/var/lib/dpkg/info/udev.postinst b/src/var/lib/dpkg/info/udev.postinst
--- a/src/var/lib/dpkg/info/udev.postinst
+++ b/src/var/lib/dpkg/info/udev.postinst
@@ -2,98 +2,51 @@
 
 set -e
 
-chrooted() {
-  if [ "$(stat -c %d/%i /)" = "$(stat -Lc %d/%i /proc/1/root 2>/dev/null)" ];
-  then
-    # the devicenumber/inode pair of / is the same as that of /sbin/init's
-    # root, so we're *not* in a chroot and hence return false.
-    return 1
-  fi
-  echo "A chroot environment has been detected, udev not started."
-  return 0
-}
-
-in_debootstrap() {
-  # debootstrap --second-stage may be run in an emulator instead of a chroot,
-  # we need to check for this special case because start-stop-daemon would
-  # not be available. (#520742)
-  if [ -d /debootstrap/ ]; then
-    echo "Being installed by debootstrap, udev not started."
-    return 0
-  fi
-  return 1
-}
-
-can_start_udevd() {
-  if [ ! -d /sys/class/ ]; then
-    echo "udev requires a mounted sysfs, not started."
-    return 1
-  fi
-  return 0
-}
-
-enable_udev() {
-  can_start_udevd || return 0
-  invoke-rc.d udev start
-}
-
-upgrade_fixes() {
-  :
-}
-
 update_hwdb() {
-  systemd-hwdb --usr update || true
+    systemd-hwdb --usr update || true
 }
 
 case "$1" in
     configure)
-    # update/create hwdb before we (re)start udev
-    update_hwdb
+        # update/create hwdb before we (re)start udev
+        update_hwdb
 
-    # Add new system groups used by udev rules
-    addgroup --quiet --system input
-    addgroup --quiet --system sgx
-
-    # Make /dev/kvm accessible to kvm group
-    addgroup --quiet --system kvm
-
-    # Make /dev/dri/renderD* accessible to render group
-    addgroup --quiet --system render
-
-    if [ -z "$2" ]; then # first install
-      if ! chrooted && ! in_debootstrap; then
-	enable_udev
-      fi
-    else # upgrades
-      upgrade_fixes "$@"
-      if ! chrooted; then
-	if can_start_udevd; then
-	  if [ -d /run/systemd/system ] ; then
-	    systemctl daemon-reload || true
-	  fi
-	  invoke-rc.d udev restart
-	fi
-      fi
-    fi
+        if dpkg --compare-versions "$2" lt-nl "254.3-1~" && [ ! -f /etc/init.d/udev ]; then
+            update-rc.d udev remove || true
+        fi
     ;;
 
     triggered)
-    update_hwdb
-    exit 0
+        update_hwdb
+        exit 0
     ;;
 esac
 
-# Automatically added by dh_installtmpfiles/13.11.4
+# Automatically added by dh_installsysusers/13.24.1
+if [ "$1" = "configure" ] || [ "$1" = "abort-upgrade" ] || [ "$1" = "abort-deconfigure" ] || [ "$1" = "abort-remove" ] ; then
+   systemd-sysusers ${DPKG_ROOT:+--root="$DPKG_ROOT"} debian-udev.conf
+fi
+# End automatically added section
+# Automatically added by dh_installtmpfiles/13.24.1
 if [ "$1" = "configure" ] || [ "$1" = "abort-upgrade" ] || [ "$1" = "abort-deconfigure" ] || [ "$1" = "abort-remove" ] ; then
 	if [ -x "$(command -v systemd-tmpfiles)" ]; then
-		systemd-tmpfiles ${DPKG_ROOT:+--root="$DPKG_ROOT"} --create static-nodes-permissions.conf >/dev/null || true
+		systemd-tmpfiles ${DPKG_ROOT:+--root="$DPKG_ROOT"} --create static-nodes-permissions.conf || true
 	fi
 fi
 # End automatically added section
-# Automatically added by dh_installinit/13.11.4
+# Automatically added by dh_installdeb/13.24.1
+dpkg-maintscript-helper rm_conffile /etc/init.d/udev 254.3-1\~ -- "$@"
+# End automatically added section
+# Automatically added by dh_installsystemd/13.24.1
 if [ "$1" = "configure" ] || [ "$1" = "abort-upgrade" ] || [ "$1" = "abort-deconfigure" ] || [ "$1" = "abort-remove" ] ; then
-	if [ -x "/etc/init.d/udev" ]; then
-		update-rc.d udev defaults >/dev/null || exit 1
+	if [ -d /run/systemd/system ]; then
+		systemctl --system daemon-reload >/dev/null || true
+		if [ -n "$2" ]; then
+			_dh_action=restart
+		else
+			_dh_action=start
+		fi
+		deb-systemd-invoke $_dh_action 'systemd-udevd.service' >/dev/null || true
 	fi
 fi
 # End automatically added section
